<?php include('includes/header.php'); ?>
        <div id="news">
            <h1>Purus Vestibulum Vulputate <br> <span class="small italic">July 22nd 2013</span></h1>
            <img src="images/news-single.png" />
            <caption><span class="gray italic small">justo odio, dapibus ac facilisis in, egestas eget quam.</span> </caption>
            <p>The organizations funded by the JRS Biodiversity Foundation are listed on the table in the right column with links to summary descriptions of the funded projects.  Since the Foundation’s initiation of its firsts grants in 2006 it has funded 33 projects totaling approximately $4 million.  Projects have been funded in Brazil, Costa Rica, Panama, Peru, India, Burkina Faso, Ghana, Kenya, Madagascar, Tanzania, and South Africa.</p>
            <p>The Foundation’s grantmaking interest is defined in its mission statement and scope.  It initiated its first funding effort with a Request for Proposal inviting exemplary organizations working in the field of biodiversity and is currently on its 4th call for proposals.  The invitations were written to advance biodiversity informatics, which the Foundation defines as the method, training, and information technologies that enable the interpretation of, and access to biodiversity data and knowledge. The Foundation has a special interest in supporting biodiversity work that cuts across traditional boundaries, especially as the field becomes increasingly data-driven, benefiting from collaboration among various environmental disciplines.</p>
            <p>The JRS Biodiversity Foundation recognizes that the field of biodiversity encompasses a wide range of activities from research science; to data collection; to aggregation, synthesis and publication of data; to interpretation and analysis of data; to the ultimate application and use of biodiversity data by end-users to effect policy change.  Within this wide range of options the Foundation sought with its initial RFP to advance projects, or parts of biodiversity informatics projects that focus on: (1) collecting data, (2) aggregating, synthesizing, publishing data, and making it more widely available to potential end users, and (3) and interpreting and gaining insights from data. </p>
        
        </div><!--end main-->
<?php include('includes/sidebar-categories.php'); ?>
<?php include('includes/footer.php'); ?>